@file:JvmName("ResourcePackExtension")

package net.warpedvoxels.core.rp.extension

import net.kyori.adventure.key.Key
import org.bukkit.Instrument
import org.bukkit.Particle

/**
 * Convert Bukkit [Instrument] to Minecraft's namespaced ID.
 */
public val Instrument.key: Key
    get() = Key.key(when (this) {
        Instrument.BANJO -> "banjo"
        Instrument.BASS_DRUM -> "basedrum"
        Instrument.BASS_GUITAR -> "bass"
        Instrument.BELL -> "bell"
        Instrument.BIT -> "bit"
        Instrument.CHIME -> "chime"
        Instrument.COW_BELL -> "cow_bell"
        Instrument.CREEPER -> "creeper"
        Instrument.CUSTOM_HEAD -> "custom_head"
        Instrument.DIDGERIDOO -> "didgeridoo"
        Instrument.DRAGON -> "dragon"
        Instrument.FLUTE -> "flute"
        Instrument.GUITAR -> "guitar"
        Instrument.PIANO -> "harp"
        Instrument.IRON_XYLOPHONE -> "iron_xylophone"
        Instrument.PIGLIN -> "piglin"
        Instrument.PLING -> "pling"
        Instrument.SKELETON -> "skeleton"
        Instrument.SNARE_DRUM -> "snare"
        Instrument.WITHER_SKELETON -> "wither_skeleton"
        Instrument.XYLOPHONE -> "xylophone"
        Instrument.STICKS -> "hat"
        Instrument.ZOMBIE -> "zombie"
    })

/**
 * Convert Bukkit [Particle] to Minecraft's namespaced ID.
 */
public val Particle.key: Key
    get() = Key.key(when (this) {
        Particle.EXPLOSION_NORMAL -> "poof"
        Particle.EXPLOSION_LARGE -> "explosion"
        Particle.EXPLOSION_HUGE -> "explosion_emitter"
        Particle.FIREWORKS_SPARK -> "firework"
        Particle.WATER_BUBBLE -> "bubble"
        Particle.WATER_SPLASH -> "splash"
        Particle.WATER_WAKE -> "fishing"
        Particle.SUSPENDED -> "underwater"
        Particle.SUSPENDED_DEPTH -> "underwater"
        Particle.CRIT -> "crit"
        Particle.CRIT_MAGIC -> "enchanted_hit"
        Particle.SMOKE_NORMAL -> "smoke"
        Particle.SMOKE_LARGE -> "large_smoke"
        Particle.SPELL -> "effect"
        Particle.SPELL_INSTANT -> "instant_effect"
        Particle.SPELL_MOB -> "entity_effect"
        Particle.SPELL_MOB_AMBIENT -> "ambient_entity_effect"
        Particle.SPELL_WITCH -> "witch"
        Particle.DRIP_WATER -> "dripping_water"
        Particle.DRIP_LAVA -> "dripping_lava"
        Particle.VILLAGER_ANGRY -> "angry_villager"
        Particle.VILLAGER_HAPPY -> "happy_villager"
        Particle.TOWN_AURA -> "mycelium"
        Particle.NOTE -> "note"
        Particle.PORTAL -> "portal"
        Particle.ENCHANTMENT_TABLE -> "enchant"
        Particle.FLAME -> "flame"
        Particle.LAVA -> "lava"
        Particle.CLOUD -> "cloud"
        Particle.REDSTONE -> "dust"
        Particle.SNOWBALL -> "item_snowball"
        Particle.SNOW_SHOVEL -> "item_snowball"
        Particle.SLIME -> "item_slime"
        Particle.HEART -> "heart"
        Particle.ITEM_CRACK -> "item"
        Particle.BLOCK_CRACK -> "block"
        Particle.BLOCK_DUST -> "block"
        Particle.WATER_DROP -> "rain"
        Particle.MOB_APPEARANCE -> "elder_guardian"
        Particle.DRAGON_BREATH -> "dragon_breath"
        Particle.END_ROD -> "end_rod"
        Particle.DAMAGE_INDICATOR -> "damage_indicator"
        Particle.SWEEP_ATTACK -> "sweep_attack"
        Particle.FALLING_DUST -> "falling_dust"
        Particle.TOTEM -> "totem_of_undying"
        Particle.SPIT -> "spit"
        Particle.SQUID_INK -> "squid_ink"
        Particle.BUBBLE_POP -> "bubble_pop"
        Particle.CURRENT_DOWN -> "current_down"
        Particle.BUBBLE_COLUMN_UP -> "bubble_column_up"
        Particle.NAUTILUS -> "nautilus"
        Particle.DOLPHIN -> "dolphin"
        Particle.SNEEZE -> "sneeze"
        Particle.CAMPFIRE_COSY_SMOKE -> "campfire_cosy_smoke"
        Particle.CAMPFIRE_SIGNAL_SMOKE -> "campfire_signal_smoke"
        Particle.COMPOSTER -> "composter"
        Particle.FLASH -> "flash"
        Particle.FALLING_LAVA -> "falling_lava"
        Particle.LANDING_LAVA -> "landing_lava"
        Particle.FALLING_WATER -> "falling_water"
        Particle.DRIPPING_HONEY -> "dripping_honey"
        Particle.FALLING_HONEY -> "falling_honey"
        Particle.LANDING_HONEY -> "landing_honey"
        Particle.FALLING_NECTAR -> "falling_nectar"
        Particle.SOUL_FIRE_FLAME -> "soul_fire_flame"
        Particle.ASH -> "ash"
        Particle.CRIMSON_SPORE -> "crimson_spore"
        Particle.WARPED_SPORE -> "warped_spore"
        Particle.SOUL -> "soul"
        Particle.DRIPPING_OBSIDIAN_TEAR -> "dripping_obsidian_tear"
        Particle.FALLING_OBSIDIAN_TEAR -> "falling_obsidian_tear"
        Particle.LANDING_OBSIDIAN_TEAR -> "landing_obsidian_tear"
        Particle.REVERSE_PORTAL -> "reverse_portal"
        Particle.WHITE_ASH -> "white_ash"
        Particle.DUST_COLOR_TRANSITION -> "dust_color_transition"
        Particle.VIBRATION -> "vibration"
        Particle.FALLING_SPORE_BLOSSOM -> "falling_spore_blossom"
        Particle.SPORE_BLOSSOM_AIR -> "spore_blossom_air"
        Particle.SMALL_FLAME -> "small_flame"
        Particle.SNOWFLAKE -> "snowflake"
        Particle.DRIPPING_DRIPSTONE_LAVA -> "dripping_dripstone_lava"
        Particle.FALLING_DRIPSTONE_LAVA -> "falling_dripstone_lava"
        Particle.DRIPPING_DRIPSTONE_WATER -> "dripping_dripstone_water"
        Particle.FALLING_DRIPSTONE_WATER -> "falling_dripstone_water"
        Particle.GLOW_SQUID_INK -> "glow_squid_ink"
        Particle.GLOW -> "glow"
        Particle.WAX_ON -> "wax_on"
        Particle.WAX_OFF -> "wax_off"
        Particle.ELECTRIC_SPARK -> "electric_spark"
        Particle.SCRAPE -> "scrape"
        Particle.BLOCK_MARKER -> "block_marker"
        Particle.SONIC_BOOM -> "sonic_boom"
        Particle.SCULK_SOUL -> "sculk_soul"
        Particle.SCULK_CHARGE -> "sculk_charge"
        Particle.SCULK_CHARGE_POP -> "sculk_charge_pop"
        Particle.SHRIEK -> "shriek"
        Particle.CHERRY_LEAVES -> "cherry_leaves"
        Particle.EGG_CRACK -> "egg_crack"
        Particle.LEGACY_BLOCK_CRACK -> "block"
        Particle.LEGACY_BLOCK_DUST -> "block"
        Particle.LEGACY_FALLING_DUST -> "falling_dust"
    })
